server:
    address: 127.0.0.1
    port:    8080
routes:
    - testservice1:
        path: /testing/
        routes:
            - route:
                address: 127.0.0.1
                port:    8081
            - route:
                address: 127.0.0.1
                port:    8082
